### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by derekwyatt** [spinn3r/noxy#15]
I'm unable to build `master` (currently at 44fcfeb) due, at least, to the inability to get many of the artemis dependencies at version `5.1-LATEST-6`.  I've tried setting them to `5.1.696` but then I get some compilation errors.

The first available sha that I can build is 70ec6c0, which I found with a `git bisect` running `mvn -Dmaven.test.skip=true package`.  But, I can't seem to get `noxy-reverse` to work with this build; everything just returns a `Bad Request`, although it can figure out that my server is available and online.

I'm really quite interested in trying `noxy-reverse` - is there any way we could get the build working?

**Comment by burtonator** [comment]
We build internally and admittedly our maven setup is a bit weird.  

If you just checkout artemis-framework and then mvn -DskipTests install them then you can build noxy.

The issue is that 5-1-LATEST-6 is essentially our 'snapshot' release.  

Once that is done  you can build.

If that doesn't work I can help document a cleaner process.  

We took the approach of not constantly changing version numbers as IntelliJ has a bug where it seems to get stuck in a compilation loop.

**Comment by derekwyatt** [comment]
Thanks a lot.  I am not able to build artemis due to:
```
[WARNING] The POM for com.spinn3r.junit.categories:artemis-junit-categories:jar:5.1-LATEST-6 is missing, no dependency information available
Downloading: http://public.maven.spinn3r.com/com/spinn3r/junit/categories/artemis-junit-categories/5.1-LATEST-6/artemis-junit-categories-5.1-LATEST-6.jar
Downloading: https://repo.maven.apache.org/maven2/com/spinn3r/junit/categories/artemis-junit-categories/5.1-LATEST-6/artemis-junit-categories-5.1-LATEST-6.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] artemis-framework .................................. SUCCESS [  0.155 s]
[INFO] artemis-json-framework ............................. FAILURE [  3.074 s]
```
And I can't find the project for `artemis-junit-categories`.  Do you know where this might be?

**Comment by burtonator** [comment]
Busted... 

Try this:

https://github.com/spinn3r/artemis-junit-categories

I just published it.  We accidentally placed it into the wrong repo.  It was meant to be OSS.

**Comment by derekwyatt** [comment]
Beautiful.  After cloning that and `metrics-kairosdb`, I was able to build.  Thanks a ton for your fast response.  I'll be testing this out tomorrow, hoping for a winner.  I've been searching for a solid and extensible Java-based reverse HTTP proxy for quite a while.

**Comment by burtonator** [comment]
ok.. noxy should probably do it for you.. it's based on little proxy which is mostly a library... not a full blown proxy framework.. but noxy wraps it and makes it more of a standalone daemon.
